services:
  studybuddy:
    container_name: studybuddy
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    command: ["uv", "run", "granian", "--interface", "asgi", "asgi.py", "--host", "0.0.0.0", "--port", "8000"]